server:
  port: 81

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/health?serverTimezone=UTC
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ymsd.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.log4j.Log4jImpl

out_put_path: E:\\projects\\projectCode\\MyHealth\\health_parent\\health_mobile\\src\\main\\resources\\static\\pages\\

#pagehelper分页插件配置 以下属性不加也可以实现分页功能
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql